Repository SeongChan-An/team6_project, pull requests merged in 2022-01, with the labels that each got.

#9 [Seongchan, ticket-#8]
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement

#12 [Seongchan, ticket-#11]
  .github/ISSUE_TEMPLATE.md
  README.md
  images/icons/Google__G__Logo 1.png
  images/icons/Group.png
  images/icons/basic-profile-img-.png
  images/icons/basic-profile.png
  images/icons/facebook.png
  images/icons/iccon-img-layers.png
  images/icons/icon- more-vertical.png
  images/icons/icon-arrow-left.png
  images/icons/icon-edit.png
  images/icons/icon-heart.png
  images/icons/icon-home-fill.png
  images/icons/icon-home.png
  images/icons/icon-image.png
  images/icons/icon-message-circle-fill.png
  images/icons/icon-message-circle.png
  images/icons/icon-post-album-off.png
  images/icons/icon-post-album-on.png
  images/icons/icon-post-list-off.png
  images/icons/icon-post-list-on.png
  images/icons/icon-search.png
  images/icons/icon-share.png
  images/icons/icon-user-fill.png
  images/icons/icon-user.png
  images/icons/img-button.png
  images/icons/message-circle.png
  images/icons/s-icon-more-vertical.png
  images/icons/upload-file.png
  images/icons/x.png
Labels: Setup

#13 Sync
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  css/reset.css
  css/styles.css
  images/dummy.txt
  images/icons/Google__G__Logo 1.png
  images/icons/Group.png
  images/icons/basic-profile-img-.png
  images/icons/basic-profile.png
  images/icons/facebook.png
  images/icons/iccon-img-layers.png
  images/icons/icon- more-vertical.png
  images/icons/icon-arrow-left.png
  images/icons/icon-edit.png
  images/icons/icon-heart.png
  images/icons/icon-home-fill.png
  images/icons/icon-home.png
  images/icons/icon-image.png
  images/icons/icon-message-circle-fill.png
  images/icons/icon-message-circle.png
  images/icons/icon-post-album-off.png
  images/icons/icon-post-album-on.png
  images/icons/icon-post-list-off.png
  images/icons/icon-post-list-on.png
  images/icons/icon-search.png
  images/icons/icon-share.png
  images/icons/icon-user-fill.png
  images/icons/icon-user.png
  images/icons/img-button.png
  images/icons/message-circle.png
  images/icons/s-icon-more-vertical.png
  images/icons/upload-file.png
  images/icons/x.png
  index.html
  src/index.js
Labels: enhancement, Setup

#14 Feature/6 login
  css/reset.css
  css/screens/login.css
  css/styles.css
  css/variables.css
  images/basic-profile-img-.png
  images/basic-profile.png
  images/icon-404.png
  images/icons/Thumbs.db
  images/img-button.png
  images/logos/full-logo.png
  images/logos/symbol-logo-W.png
  images/logos/symbol-logo-gray.png
  images/sns/Google.png
  images/sns/facebook.png
  images/sns/message.png
  images/tab-menu/icon-edit.png
  images/tab-menu/icon-home-fill.png
  images/tab-menu/icon-home.png
  images/tab-menu/icon-message-circle-fill.png
  images/tab-menu/icon-message-circle.png
  images/tab-menu/icon-user-fill.png
  images/tab-menu/icon-user.png
  images/upload-file.png
  index.html
Labels: enhancement, Setup

#18 Feature/17 signup
  css/components/modules.css
  css/screens/login-email.css
  index.html
  login-email.html
  modules.html
  signup.html
Labels: enhancement

#19 [Seongchan, ticket-#10]
  css/components/header-main.css
  css/components/modules.css
  css/components/navbar.css
  css/screens/home-main.css
  css/style.css
  modules.html
  views/home.html
Labels: enhancement

#21 Feature/20 set profile
  css/components/modules.css
  css/screens/set-profile.css
  css/style.css
  set-profile.html
Labels: enhancement

#25 Feature/24 refactoring
  css/screens/home-main.css
  css/style.css
  views/home.html
Labels: bug
